source "https://rubygems.org"

ruby "2.2.2"

gem "rails", "4.2.3"
gem "pg"
gem "figaro"
gem "simple_form"
gem "country_select"
gem "high_voltage"
gem "devise"
# gem "pundit"
gem "paperclip"
gem "aws-sdk", "< 2.0"
gem 'faker'
gem "jquery-rails"
gem "sass-rails", "~> 5.0"
gem "uglifier"
gem "bootstrap-sass"
gem "font-awesome-sass"
gem 'omniauth-facebook'
gem "koala", "~> 2.2"
gem 'autoprefixer-rails'

gem 'react-rails', '1.2.0'
gem 'js-routes'

gem "rails-i18n"
gem "devise-i18n"
gem "devise-i18n-views"

gem 'twilio-ruby'

source 'https://rails-assets.org' do
  gem 'rails-assets-classnames'
  gem "rails-assets-alt"
  gem "rails-assets-axios"
  gem 'rails-assets-pubsub-js'
end

group :development, :test do
  gem "spring"
  gem "annotate"
  gem "binding_of_caller"
  gem "better_errors"
  gem "quiet_assets"
  gem "pry-byebug"
  gem "pry-rails"
  gem "letter_opener"
  gem "bullet"
end

group :production do
  gem "rails_12factor"
  gem "puma"
  gem "rack-timeout"
end
